server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///cloud-user?useSSL=false
    username: root
    pasword:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: UserService
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8848/eureka
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
