server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql:///cloud-order?useSSL=false
    username: root
    pasword:
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: OrderService
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8848/eureka
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tb_
userservice: # 给需要调用的微服务配置负载均衡规则，orderservice服务去调用userservice服务
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 负载均衡规则
ribbon:
  eureka:
    enabled: true #开启饥饿加载
    clients: #指定饥饿加载的服务名称
      - UserService